name: 'gpt-review'
description: 'Review your PRs with a GPT Model from Azure Open AI'
branding:
  icon: 'eye'
  color: 'gray-dark'
inputs:
  GITHUB_TOKEN:
    description: 'Derivative token for using the GitHub REST API'
    required: true
  OPENAI_API_KEY:
    description: 'OpenAI API Key'
    required: true
  OPENAI_ORG_KEY:
    description: 'OpenAI Organization ID'
    required: true
  AZURE_OPENAI_API:
    description: 'URL of custom Azure Open AI API'
    required: false
  AZURE_OPENAI_API_KEY:
    description: 'Key of custom Azure Open AI API'
    required: false

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install gpt-review
        shell: bash
        run: |
          sudo apt-get update
          python3 -m venv .env
          source .env/bin/activate
          python -m pip install --upgrade pip
          python -m pip install gpt-review

      - name: Review PR and make comment
        shell: bash
        run: |
          source .env/bin/activate

          gpt github review \
            --access-token $GITHUB_TOKEN \
            --pull-request $PATCH_PR \
            --repository $PATCH_REPO
        env:
          ACTION_REF: ${{ github.action_ref || env.BRANCH }}
          GIT_COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
          LINK: "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
          OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
          OPENAI_ORG_KEY: ${{ inputs.OPENAI_ORG_KEY }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          BRANCH:  ${{ env.BRANCH }}
          AZURE_OPENAI_API_KEY: ${{ inputs.AZURE_OPENAI_API_KEY || '' }}
          AZURE_OPENAI_API: ${{ inputs.AZURE_OPENAI_API || '' }}
          PATCH_PR: ${{ github.event.pull_request.number }}
          PATCH_REPO: ${{ github.repository }}
          FULL_SUMMARY: true
          FILE_SUMMARY: false
          TEST_SUMMARY: false
          BUG_SUMMARY: false
          RISK_SUMMARY: false
          RISK_BREAKING: false

