"""A prompt for the GPT Review task."""
from gpt_review.prompts.prompt import Prompt


class ReviewPrompt(Prompt):
    """A prompt for the GPT review task."""

    prompt_prefix: str = """Summarize the following file changed in a pull request submitted by a developer on GitHub,
focusing on major modifications, additions, deletions, and any significant updates within the files. Do not include the
file name in the summary and list the summary with bullet points"""


class ReviewPrompt2(ReviewPrompt):
    """An improved prompt for the GPT review task generated by GPT."""

    prompt_prefix: str = """Summarize the following file changed in a pull request submitted by a developer on GitHub,
focusing on major modifications, additions, deletions, and any significant updates within the files.
Do not include the file name in the summary and list the summary with bullet points
"""
    system_message: str = "You are an experienced software developer."
    examples: list = [
        {
            "role": "user",
            "content": """
""",
        },
        {
            "role": "assistant",
            "content": """
""",
        },
    ]
