"""Constants"""

MIN_MAX_TOKENS_VALUE = 1
MAX_MAX_TOKENS_VALUE = 4000
MIN_TEMPERATURE_VALUE = 0
MAX_TEMPERATURE_VALUE = 1
MIN_TOP_P_VALUE = 0
MAX_TOP_P_VALUE = 1
MIN_FREQUENCY_PENALTY_VALUE = 0
MAX_FREQUENCY_PENALTY_VALUE = 2
MIN_PRESENCE_PENALTY_VALUE = 0
MAX_PRESENCE_PENALTY_VALUE = 2
