name: GitHub Actions Version Updater

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    # Automatically run on every Sunday
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.PAT }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.7.4
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.PAT }}
          pull_request_title: "ci: Update GitHub Actions to Latest Version"
